---
- name: Aprovisionador de ansible para configurar la VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  tasks:
    - import_tasks: ansible/ejercicio1/main.yml
    - import_tasks: ansible/ejercicio2/main.yml
    - import_tasks: ansible/ejercicio3/main.yml
    - import_tasks: ansible/ejercicio4/main.yml
    - import_tasks: ansible/ejercicio5/main.yml
  handlers:
    - import_tasks: handlers/main.yml